# Generated by Django 3.2.25 on 2025-02-28 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_blogpost_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='constent',
            new_name='content',
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
